include:
  # Infrastructure / backend
  - path: ./compose/services/auth-db.yaml
    project_directory: .
    env_file: ./.env

  - path: ./compose/services/kafka.yaml
    project_directory: .
    env_file: ./.env

  - path: ./compose/services/auth-migrations-job.yaml
    project_directory: .
    env_file: ./.env

  - path: ./compose/services/auth-service.yaml
    project_directory: .
    env_file: ./.env

  # UI
  - path: ./compose/ui/pgadmin.yaml
    project_directory: .
    env_file: ./.env

  - path: ./compose/ui/kafka-ui.yaml
    project_directory: .
    env_file: ./.env
